version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - docker-compose build --no-cache
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml run --rm front /build.sh
  post_build:
    commands:
      - aws s3 sync book-clipper/dist/ s3://$DEPLOY_BUCKET_NAME --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"