version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - docker-compose build --no-cache
      - docker-compose run --rm front yarn run generate
  post_build:
    commands:
      - ls -al book-clipper
      - aws s3 sync book-clipper/dist/ s3://$DEPLOY_BUCKET_NAME --delete