version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - ls -al
      - pwd
      - whoami
      - docker-compose run --rm front yarn run generate
  post_build:
    commands:
      - aws s3 sync book-clipper/dist/ s3://$DEPLOY_BUCKET_NAME —-delete